// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eagletechapi.Contexts;

#nullable disable

namespace eagletechapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250908180756_atualizacaoUser")]
    partial class atualizacaoUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eagletechapi.models.Chatbot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("NumeroChamado")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Chatbots");
                });

            modelBuilder.Entity("eagletechapi.models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ChatbotId")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatbotId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("eagletechapi.models.chamado.Chamado", b =>
                {
                    b.Property<long>("NumeroChamado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Abertura")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<long?>("ChatbotId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fechamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteMatricula")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TecnicoMatricula")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NumeroChamado");

                    b.HasIndex("ChatbotId");

                    b.HasIndex("SolicitanteMatricula");

                    b.HasIndex("TecnicoMatricula");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("eagletechapi.models.usuario.Usuario", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Funcao")
                        .HasColumnType("int");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Matricula");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("eagletechapi.models.Message", b =>
                {
                    b.HasOne("eagletechapi.models.Chatbot", "Chatbot")
                        .WithMany("Conversation")
                        .HasForeignKey("ChatbotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chatbot");
                });

            modelBuilder.Entity("eagletechapi.models.chamado.Chamado", b =>
                {
                    b.HasOne("eagletechapi.models.Chatbot", "Chatbot")
                        .WithMany()
                        .HasForeignKey("ChatbotId");

                    b.HasOne("eagletechapi.models.usuario.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteMatricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eagletechapi.models.usuario.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoMatricula");

                    b.Navigation("Chatbot");

                    b.Navigation("Solicitante");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("eagletechapi.models.Chatbot", b =>
                {
                    b.Navigation("Conversation");
                });
#pragma warning restore 612, 618
        }
    }
}
