name: CI/CD - Eagletech

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build e push backend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/eagletechapi ./eagletechapi
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eagletechapi

      - name: Build e push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/eagletechclient ./eagletechclient
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eagletechclient

      - name: Deploy na EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            docker-compose pull
            docker-compose up -d --remove-orphans
